name: Publish Release

on:
  release:
    types: [created]
env:
    ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
    ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
    ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
    ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -   uses: actions/checkout@v3
    -   name: set up JDK 17
        uses: actions/setup-java@v3
        with:
            distribution: 'corretto'
            java-version: '17'
            cache: 'gradle'
    -   name: Grant execute permission for gradlew
        run: chmod +x gradlew
    -   name: Generate Javadoc
        run: ./gradlew javaDocReleaseGeneration --no-parallel
    -   name: Release artifacts
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
